{RG[bg[1], {-1, 1, -1, 1, 1, -1, 1, -1}, 
   {{p[1] -> p[1], p[2] -> p[3], p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4]}, 
    {p[1] -> p[1], p[2] -> p[3], p[3] -> p[4], p[4] -> p[2], p[5] -> p[5], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][4], \[Epsilon][4] -> \[Epsilon][2]}, 
    {p[1] -> p[2], p[2] -> p[4], p[3] -> p[1], p[4] -> p[3], p[5] -> -p[5], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][4], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][3]}, 
    {p[1] -> p[2], p[2] -> p[4], p[3] -> p[3], p[4] -> p[1], p[5] -> -p[5], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][4], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][1]}, 
    {p[1] -> p[3], p[2] -> p[1], p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4]}, 
    {p[1] -> p[3], p[2] -> p[1], p[3] -> p[4], p[4] -> p[2], p[5] -> p[5], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][4], \[Epsilon][4] -> \[Epsilon][2]}, 
    {p[1] -> p[4], p[2] -> p[2], p[3] -> p[1], p[4] -> p[3], p[5] -> -p[5], 
     \[Epsilon][1] -> \[Epsilon][4], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][3]}, 
    {p[1] -> p[4], p[2] -> p[2], p[3] -> p[3], p[4] -> p[1], p[5] -> -p[5], 
     \[Epsilon][1] -> \[Epsilon][4], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][1]}}] + 
  RG[bg[1], {1, -1, -1, 1, 1, -1, -1, 1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][4], \[Epsilon][4] -> \[Epsilon][3]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][4], \[Epsilon][4] -> \[Epsilon][3]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[1], p[4] -> p[2], p[5] -> -p[5], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][4], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][2]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[2], p[4] -> p[1], p[5] -> -p[5], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][4], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][1]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[1], p[4] -> p[2], p[5] -> -p[5], 
     \[Epsilon][1] -> \[Epsilon][4], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][2]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[2], p[4] -> p[1], p[5] -> -p[5], 
     \[Epsilon][1] -> \[Epsilon][4], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][1]}}] + 
  RG[bg[1], {1, -1, 1, -1, -1, 1, -1, 1}, 
   {{p[1] -> p[1], p[2] -> p[4], p[3] -> p[2], p[4] -> p[3], p[5] -> p[5], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][4], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][3]}, 
    {p[1] -> p[1], p[2] -> p[4], p[3] -> p[3], p[4] -> p[2], p[5] -> p[5], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][4], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][2]}, 
    {p[1] -> p[2], p[2] -> p[3], p[3] -> p[1], p[4] -> p[4], p[5] -> -p[5], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4]}, 
    {p[1] -> p[2], p[2] -> p[3], p[3] -> p[4], p[4] -> p[1], p[5] -> -p[5], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][4], \[Epsilon][4] -> \[Epsilon][1]}, 
    {p[1] -> p[3], p[2] -> p[2], p[3] -> p[1], p[4] -> p[4], p[5] -> -p[5], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4]}, 
    {p[1] -> p[3], p[2] -> p[2], p[3] -> p[4], p[4] -> p[1], p[5] -> -p[5], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][4], \[Epsilon][4] -> \[Epsilon][1]}, 
    {p[1] -> p[4], p[2] -> p[1], p[3] -> p[2], p[4] -> p[3], p[5] -> p[5], 
     \[Epsilon][1] -> \[Epsilon][4], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][3]}, 
    {p[1] -> p[4], p[2] -> p[1], p[3] -> p[3], p[4] -> p[2], p[5] -> p[5], 
     \[Epsilon][1] -> \[Epsilon][4], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][2]}}]}
