{RG[bg[1], {-1, 1, 1, -1, 1, -1, 1, -1, -1, 1}, 
   {{p[1] -> p[1], p[2] -> p[3], p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[5], 
     p[3] -> p[4], p[4] -> p[2], p[5] -> p[3], p[6] -> -p[10], p[7] -> -p[8], 
     p[8] -> -p[7], p[9] -> -p[9], p[10] -> -p[6], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][4], \[Epsilon][4] -> \[Epsilon][2], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[2], p[2] -> p[3], 
     p[3] -> p[1], p[4] -> p[5], p[5] -> p[4], p[6] -> p[8], p[7] -> p[9], 
     p[8] -> p[6], p[9] -> p[7], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][5], 
     \[Epsilon][5] -> \[Epsilon][4]}, {p[1] -> p[2], p[2] -> p[4], 
     p[3] -> p[5], p[4] -> p[1], p[5] -> p[3], p[6] -> p[10], p[7] -> -p[6], 
     p[8] -> -p[9], p[9] -> -p[7], p[10] -> -p[8], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][4], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][1], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[3], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[2], p[6] -> p[7], p[7] -> p[6], 
     p[8] -> -p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[3], p[2] -> p[2], 
     p[3] -> p[4], p[4] -> p[5], p[5] -> p[1], p[6] -> p[9], p[7] -> p[8], 
     p[8] -> -p[6], p[9] -> p[10], p[10] -> -p[7], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][4], \[Epsilon][4] -> \[Epsilon][5], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[4], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[1], p[5] -> p[5], p[6] -> -p[6], p[7] -> p[10], 
     p[8] -> p[9], p[9] -> p[8], p[10] -> p[7], \[Epsilon][1] -> 
      \[Epsilon][4], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][1], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[4], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[3], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[9], 
     p[8] -> -p[10], p[9] -> -p[8], p[10] -> p[6], 
     \[Epsilon][1] -> \[Epsilon][4], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][3], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[5], p[2] -> p[1], 
     p[3] -> p[3], p[4] -> p[2], p[5] -> p[4], p[6] -> -p[8], p[7] -> -p[10], 
     p[8] -> p[7], p[9] -> p[6], p[10] -> p[9], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][2], 
     \[Epsilon][5] -> \[Epsilon][4]}, {p[1] -> p[5], p[2] -> p[4], 
     p[3] -> p[2], p[4] -> p[3], p[5] -> p[1], p[6] -> -p[9], p[7] -> -p[7], 
     p[8] -> p[10], p[9] -> -p[6], p[10] -> p[8], 
     \[Epsilon][1] -> \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][4], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][3], 
     \[Epsilon][5] -> \[Epsilon][1]}}] + 
  RG[bg[1], {1, -1, -1, 1, -1, 1, -1, 1, 1, -1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[5], 
     p[3] -> p[4], p[4] -> p[3], p[5] -> p[2], p[6] -> -p[10], p[7] -> -p[8], 
     p[8] -> -p[7], p[9] -> -p[9], p[10] -> -p[6], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][4], \[Epsilon][4] -> \[Epsilon][3], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[2], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], p[6] -> p[7], p[7] -> p[6], 
     p[8] -> -p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[2], p[2] -> p[3], 
     p[3] -> p[4], p[4] -> p[5], p[5] -> p[1], p[6] -> p[9], p[7] -> p[8], 
     p[8] -> -p[6], p[9] -> p[10], p[10] -> -p[7], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][4], \[Epsilon][4] -> \[Epsilon][5], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[3], p[2] -> p[2], 
     p[3] -> p[1], p[4] -> p[5], p[5] -> p[4], p[6] -> p[8], p[7] -> p[9], 
     p[8] -> p[6], p[9] -> p[7], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][5], 
     \[Epsilon][5] -> \[Epsilon][4]}, {p[1] -> p[3], p[2] -> p[4], 
     p[3] -> p[5], p[4] -> p[1], p[5] -> p[2], p[6] -> p[10], p[7] -> -p[6], 
     p[8] -> -p[9], p[9] -> -p[7], p[10] -> -p[8], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][4], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][1], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[4], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], p[6] -> -p[6], p[7] -> p[10], 
     p[8] -> p[9], p[9] -> p[8], p[10] -> p[7], \[Epsilon][1] -> 
      \[Epsilon][4], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][1], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[4], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[2], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[9], 
     p[8] -> -p[10], p[9] -> -p[8], p[10] -> p[6], 
     \[Epsilon][1] -> \[Epsilon][4], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][2], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[5], p[2] -> p[1], 
     p[3] -> p[2], p[4] -> p[3], p[5] -> p[4], p[6] -> -p[8], p[7] -> -p[10], 
     p[8] -> p[7], p[9] -> p[6], p[10] -> p[9], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][3], 
     \[Epsilon][5] -> \[Epsilon][4]}, {p[1] -> p[5], p[2] -> p[4], 
     p[3] -> p[3], p[4] -> p[2], p[5] -> p[1], p[6] -> -p[9], p[7] -> -p[7], 
     p[8] -> p[10], p[9] -> -p[6], p[10] -> p[8], 
     \[Epsilon][1] -> \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][4], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][2], 
     \[Epsilon][5] -> \[Epsilon][1]}}] + RG[bg[2], {1, -1, 1, -1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[4], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[1], p[5] -> p[5], p[6] -> p[6], p[7] -> p[10], 
     p[8] -> p[9], p[9] -> p[8], p[10] -> p[7], \[Epsilon][1] -> 
      \[Epsilon][4], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][1], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[4], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], p[6] -> p[6], p[7] -> p[10], 
     p[8] -> p[9], p[9] -> p[8], p[10] -> p[7], \[Epsilon][1] -> 
      \[Epsilon][4], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][1], 
     \[Epsilon][5] -> \[Epsilon][5]}}], 
 RG[bg[2], {-1, 1, -1, 1}, {{p[1] -> p[4], p[2] -> p[2], p[3] -> p[3], 
     p[4] -> p[5], p[5] -> p[1], p[6] -> p[6], p[7] -> p[10], p[8] -> p[9], 
     p[9] -> p[8], p[10] -> -p[7], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][5], \[Epsilon][5] -> \[Epsilon][1]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[2], p[4] -> p[5], p[5] -> p[1], 
     p[6] -> p[6], p[7] -> p[10], p[8] -> p[9], p[9] -> p[8], p[10] -> -p[7], 
     \[Epsilon][1] -> \[Epsilon][4], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][5], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> -p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> -p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}}] + RG[bg[2], {1, -1, 1, -1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[4], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[1], p[5] -> p[5], p[6] -> p[6], p[7] -> p[10], 
     p[8] -> p[9], p[9] -> p[8], p[10] -> p[7], \[Epsilon][1] -> 
      \[Epsilon][4], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][1], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[4], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], p[6] -> p[6], p[7] -> p[10], 
     p[8] -> p[9], p[9] -> p[8], p[10] -> p[7], \[Epsilon][1] -> 
      \[Epsilon][4], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][1], 
     \[Epsilon][5] -> \[Epsilon][5]}}] + 
  RG[bg[3], {1, -1, -1, 1, 1, -1, -1, 1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[2], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> -p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[2], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> -p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[3], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> -p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[3], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> -p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}}], 
 RG[bg[2], {-1, 1, -1, 1}, {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], 
     p[4] -> p[5], p[5] -> p[4], p[6] -> p[6], p[7] -> p[9], p[8] -> -p[8], 
     p[9] -> p[7], p[10] -> -p[10], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][5], \[Epsilon][5] -> \[Epsilon][4]}, 
    {p[1] -> p[1], p[2] -> p[3], p[3] -> p[2], p[4] -> p[5], p[5] -> p[4], 
     p[6] -> p[6], p[7] -> p[9], p[8] -> -p[8], p[9] -> p[7], 
     p[10] -> -p[10], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][5], \[Epsilon][5] -> \[Epsilon][4]}, 
    {p[1] -> p[5], p[2] -> p[2], p[3] -> p[3], p[4] -> p[1], p[5] -> p[4], 
     p[6] -> p[6], p[7] -> -p[10], p[8] -> p[7], p[9] -> -p[8], 
     p[10] -> p[9], \[Epsilon][1] -> \[Epsilon][5], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][4]}, 
    {p[1] -> p[5], p[2] -> p[3], p[3] -> p[2], p[4] -> p[1], p[5] -> p[4], 
     p[6] -> p[6], p[7] -> -p[10], p[8] -> p[7], p[9] -> -p[8], 
     p[10] -> p[9], \[Epsilon][1] -> \[Epsilon][5], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][4]}}] + 
  RG[bg[2], {1, -1, 1, -1}, {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], 
     p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], 
     p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5]}, 
    {p[1] -> p[1], p[2] -> p[3], p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[4], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[1], p[5] -> p[5], p[6] -> p[6], p[7] -> p[10], 
     p[8] -> p[9], p[9] -> p[8], p[10] -> p[7], \[Epsilon][1] -> 
      \[Epsilon][4], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][1], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[4], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], p[6] -> p[6], p[7] -> p[10], 
     p[8] -> p[9], p[9] -> p[8], p[10] -> p[7], \[Epsilon][1] -> 
      \[Epsilon][4], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][1], 
     \[Epsilon][5] -> \[Epsilon][5]}}] + RG[bg[4], {1, -1, -1, 1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[5], p[5] -> p[4], p[6] -> p[6], p[7] -> p[9], 
     p[8] -> p[8], p[9] -> p[7], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][5], 
     \[Epsilon][5] -> \[Epsilon][4]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[5], p[5] -> p[4], p[6] -> p[6], p[7] -> p[9], 
     p[8] -> p[8], p[9] -> p[7], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][5], 
     \[Epsilon][5] -> \[Epsilon][4]}}], 
 RG[bg[3], {1, -1, -1, 1, 1, -1, -1, 1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> -p[8], p[9] -> -p[10], 
     p[10] -> -p[9], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5]}, 
    {p[1] -> p[1], p[2] -> p[3], p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> -p[8], p[9] -> -p[10], 
     p[10] -> -p[9], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], 
     p[6] -> -p[7], p[7] -> -p[6], p[8] -> p[8], p[9] -> p[9], 
     p[10] -> p[10], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][3]}, 
    {p[1] -> p[2], p[2] -> p[5], p[3] -> p[1], p[4] -> p[4], p[5] -> p[3], 
     p[6] -> -p[7], p[7] -> -p[6], p[8] -> p[8], p[9] -> p[9], 
     p[10] -> p[10], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][5], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][3]}, 
    {p[1] -> p[3], p[2] -> p[1], p[3] -> p[5], p[4] -> p[4], p[5] -> p[2], 
     p[6] -> -p[7], p[7] -> -p[6], p[8] -> p[8], p[9] -> p[9], 
     p[10] -> p[10], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][2]}, 
    {p[1] -> p[3], p[2] -> p[5], p[3] -> p[1], p[4] -> p[4], p[5] -> p[2], 
     p[6] -> -p[7], p[7] -> -p[6], p[8] -> p[8], p[9] -> p[9], 
     p[10] -> p[10], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][5], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][2]}, 
    {p[1] -> p[5], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> -p[8], p[9] -> -p[10], 
     p[10] -> -p[9], \[Epsilon][1] -> \[Epsilon][5], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][1]}, 
    {p[1] -> p[5], p[2] -> p[3], p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> -p[8], p[9] -> -p[10], 
     p[10] -> -p[9], \[Epsilon][1] -> \[Epsilon][5], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][1]}}] + 
  RG[bg[3], {1, -1, -1, 1, 1, -1, -1, 1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[2], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> -p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[2], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> -p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[3], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> -p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[3], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> -p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}}] + 
  RG[bg[5], {1, 1, -1, -1, -1, -1, 1, 1, 1, 1, -1, -1, -1, -1, 1, 1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[2], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[2], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[2], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[2], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[3], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[3], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[3], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[3], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}}], 
 RG[bg[3], {1, -1, -1, 1, 1, -1, -1, 1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[2], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> -p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[2], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> -p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[3], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> -p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[3], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> -p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}}] + 
  RG[bg[3], {1, -1, -1, 1, 1, -1, -1, 1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[2], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> -p[10], p[9] -> -p[8], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[2], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> -p[10], p[9] -> -p[8], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[3], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> -p[10], p[9] -> -p[8], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[3], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> -p[10], p[9] -> -p[8], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}}] + 
  RG[bg[6], {1, 1, -1, -1, -1, -1, 1, 1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}}], 
 RG[bg[4], {-1, 1, 1, -1}, {{p[1] -> p[2], p[2] -> p[1], p[3] -> p[3], 
     p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], 
     p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[3], p[4] -> p[5], p[5] -> p[4], 
     p[6] -> p[6], p[7] -> p[9], p[8] -> p[8], p[9] -> p[7], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][5], 
     \[Epsilon][5] -> \[Epsilon][4]}, {p[1] -> p[2], p[2] -> p[3], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[2], p[2] -> p[3], 
     p[3] -> p[1], p[4] -> p[5], p[5] -> p[4], p[6] -> p[6], p[7] -> p[9], 
     p[8] -> p[8], p[9] -> p[7], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][5], 
     \[Epsilon][5] -> \[Epsilon][4]}}] + RG[bg[4], {1, -1, -1, 1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[5], p[5] -> p[4], p[6] -> p[6], p[7] -> p[9], 
     p[8] -> p[8], p[9] -> p[7], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][5], 
     \[Epsilon][5] -> \[Epsilon][4]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[5], p[5] -> p[4], p[6] -> p[6], p[7] -> p[9], 
     p[8] -> p[8], p[9] -> p[7], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][5], 
     \[Epsilon][5] -> \[Epsilon][4]}}] + RG[bg[4], {1, -1, -1, 1}, 
   {{p[1] -> p[3], p[2] -> p[1], p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[3], p[2] -> p[1], 
     p[3] -> p[2], p[4] -> p[5], p[5] -> p[4], p[6] -> p[6], p[7] -> p[9], 
     p[8] -> p[8], p[9] -> p[7], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][5], 
     \[Epsilon][5] -> \[Epsilon][4]}, {p[1] -> p[3], p[2] -> p[2], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[3], p[2] -> p[2], 
     p[3] -> p[1], p[4] -> p[5], p[5] -> p[4], p[6] -> p[6], p[7] -> p[9], 
     p[8] -> p[8], p[9] -> p[7], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][5], 
     \[Epsilon][5] -> \[Epsilon][4]}}], 
 RG[bg[4], {1, -1, -1, 1}, {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], 
     p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], 
     p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[5], p[5] -> p[4], 
     p[6] -> p[6], p[7] -> p[9], p[8] -> p[8], p[9] -> p[7], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][5], 
     \[Epsilon][5] -> \[Epsilon][4]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[5], p[5] -> p[4], p[6] -> p[6], p[7] -> p[9], 
     p[8] -> p[8], p[9] -> p[7], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][5], 
     \[Epsilon][5] -> \[Epsilon][4]}}] + RG[bg[4], {1, -1, -1, 1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> -p[10], 
     p[10] -> -p[9], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[5], p[5] -> p[4], 
     p[6] -> p[6], p[7] -> -p[10], p[8] -> p[8], p[9] -> p[7], p[10] -> p[9], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][5], 
     \[Epsilon][5] -> \[Epsilon][4]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[5], p[5] -> p[4], p[6] -> p[6], p[7] -> -p[10], 
     p[8] -> p[8], p[9] -> p[7], p[10] -> p[9], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][5], 
     \[Epsilon][5] -> \[Epsilon][4]}}] + RG[bg[7], {1, 1, -1, -1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}}], 
 RG[bg[4], {1, -1, -1, 1}, {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], 
     p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], 
     p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[5], p[5] -> p[4], 
     p[6] -> p[6], p[7] -> p[9], p[8] -> p[8], p[9] -> p[7], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][5], 
     \[Epsilon][5] -> \[Epsilon][4]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[5], p[5] -> p[4], p[6] -> p[6], p[7] -> p[9], 
     p[8] -> p[8], p[9] -> p[7], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][5], 
     \[Epsilon][5] -> \[Epsilon][4]}}] + RG[bg[4], {1, -1, -1, 1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[9], p[8] -> p[8], p[9] -> p[7], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[5], p[5] -> p[4], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][5], 
     \[Epsilon][5] -> \[Epsilon][4]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[9], 
     p[8] -> p[8], p[9] -> p[7], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[5], p[5] -> p[4], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][5], 
     \[Epsilon][5] -> \[Epsilon][4]}}] + 
  RG[bg[6], {1, 1, -1, -1, -1, -1, 1, 1}, 
   {{p[1] -> p[4], p[2] -> p[2], p[3] -> p[3], p[4] -> p[1], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> -p[10], p[8] -> p[7], p[9] -> -p[8], 
     p[10] -> p[9], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][5]}, 
    {p[1] -> p[4], p[2] -> p[2], p[3] -> p[3], p[4] -> p[1], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> -p[10], p[8] -> p[9], p[9] -> -p[8], 
     p[10] -> p[7], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][5]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> -p[10], p[8] -> p[7], p[9] -> -p[8], 
     p[10] -> p[9], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][5]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> -p[10], p[8] -> p[9], p[9] -> -p[8], 
     p[10] -> p[7], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][5]}, 
    {p[1] -> p[5], p[2] -> p[2], p[3] -> p[3], p[4] -> p[1], p[5] -> p[4], 
     p[6] -> p[6], p[7] -> -p[10], p[8] -> p[7], p[9] -> -p[8], 
     p[10] -> p[9], \[Epsilon][1] -> \[Epsilon][5], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][4]}, 
    {p[1] -> p[5], p[2] -> p[2], p[3] -> p[3], p[4] -> p[1], p[5] -> p[4], 
     p[6] -> p[6], p[7] -> -p[10], p[8] -> p[9], p[9] -> -p[8], 
     p[10] -> p[7], \[Epsilon][1] -> \[Epsilon][5], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][4]}, 
    {p[1] -> p[5], p[2] -> p[3], p[3] -> p[2], p[4] -> p[1], p[5] -> p[4], 
     p[6] -> p[6], p[7] -> -p[10], p[8] -> p[7], p[9] -> -p[8], 
     p[10] -> p[9], \[Epsilon][1] -> \[Epsilon][5], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][4]}, 
    {p[1] -> p[5], p[2] -> p[3], p[3] -> p[2], p[4] -> p[1], p[5] -> p[4], 
     p[6] -> p[6], p[7] -> -p[10], p[8] -> p[9], p[9] -> -p[8], 
     p[10] -> p[7], \[Epsilon][1] -> \[Epsilon][5], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][4]}}], 
 RG[bg[5], {1, 1, -1, -1, -1, -1, 1, 1, 1, 1, -1, -1, -1, -1, 1, 1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[2], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[2], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[2], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[2], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[3], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[3], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[3], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[3], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}}] + RG[bg[7], {-1, -1, 1, 1}, 
   {{p[1] -> p[3], p[2] -> p[1], p[3] -> p[5], p[4] -> p[4], p[5] -> p[2], 
     p[6] -> -p[7], p[7] -> -p[8], p[8] -> p[6], p[9] -> p[9], 
     p[10] -> p[10], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][2]}, 
    {p[1] -> p[3], p[2] -> p[1], p[3] -> p[5], p[4] -> p[4], p[5] -> p[2], 
     p[6] -> -p[7], p[7] -> -p[8], p[8] -> p[6], p[9] -> -p[10], 
     p[10] -> -p[9], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][2]}, 
    {p[1] -> p[3], p[2] -> p[5], p[3] -> p[1], p[4] -> p[4], p[5] -> p[2], 
     p[6] -> -p[7], p[7] -> -p[8], p[8] -> p[6], p[9] -> p[9], 
     p[10] -> p[10], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][5], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][2]}, 
    {p[1] -> p[3], p[2] -> p[5], p[3] -> p[1], p[4] -> p[4], p[5] -> p[2], 
     p[6] -> -p[7], p[7] -> -p[8], p[8] -> p[6], p[9] -> -p[10], 
     p[10] -> -p[9], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][5], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][2]}}] + 
  RG[bg[7], {1, 1, -1, -1}, {{p[1] -> p[2], p[2] -> p[1], p[3] -> p[5], 
     p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[8], p[8] -> p[6], 
     p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][3]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], 
     p[6] -> -p[7], p[7] -> -p[8], p[8] -> p[6], p[9] -> -p[10], 
     p[10] -> -p[9], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][3]}, 
    {p[1] -> p[2], p[2] -> p[5], p[3] -> p[1], p[4] -> p[4], p[5] -> p[3], 
     p[6] -> -p[7], p[7] -> -p[8], p[8] -> p[6], p[9] -> p[9], 
     p[10] -> p[10], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][5], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][3]}, 
    {p[1] -> p[2], p[2] -> p[5], p[3] -> p[1], p[4] -> p[4], p[5] -> p[3], 
     p[6] -> -p[7], p[7] -> -p[8], p[8] -> p[6], p[9] -> -p[10], 
     p[10] -> -p[9], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][5], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][3]}}], 
 RG[bg[5], {-1, -1, 1, 1, 1, 1, -1, -1, -1, -1, 1, 1, 1, 1, -1, -1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> -p[9], 
     p[10] -> -p[10], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[10], p[10] -> p[9], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[9], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[10], p[10] -> p[9], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[2], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> -p[9], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[2], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> p[10], p[10] -> p[9], \[Epsilon][1] -> 
      \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[2], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> -p[9], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[2], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> p[10], p[10] -> p[9], \[Epsilon][1] -> 
      \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[3], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> -p[9], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[3], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> p[10], p[10] -> p[9], \[Epsilon][1] -> 
      \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[3], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> -p[9], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[3], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> p[10], p[10] -> p[9], \[Epsilon][1] -> 
      \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[9], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[10], p[10] -> p[9], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[9], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[10], p[10] -> p[9], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}}] + 
  RG[bg[5], {1, 1, -1, -1, -1, -1, 1, 1, 1, 1, -1, -1, -1, -1, 1, 1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[2], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[2], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[2], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[2], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[3], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][3]}, {p[1] -> p[3], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[3], p[2] -> p[1], 
     p[3] -> p[5], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][5], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[3], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[3], p[2] -> p[5], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[2], p[6] -> -p[7], p[7] -> -p[6], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][5], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][2]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}}], 
 RG[bg[6], {-1, -1, 1, 1, 1, 1, -1, -1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     p[6] -> -p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][4], \[Epsilon][4] -> \[Epsilon][3], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[2], 
     p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], p[6] -> -p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][4], \[Epsilon][4] -> \[Epsilon][3], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[4], 
     p[3] -> p[2], p[4] -> p[3], p[5] -> p[5], p[6] -> -p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][4], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][3], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[4], 
     p[3] -> p[2], p[4] -> p[3], p[5] -> p[5], p[6] -> -p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][4], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][3], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[4], p[4] -> p[3], p[5] -> p[1], p[6] -> -p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][4], \[Epsilon][4] -> \[Epsilon][3], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[4], p[4] -> p[3], p[5] -> p[1], p[6] -> -p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][4], \[Epsilon][4] -> \[Epsilon][3], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[4], 
     p[3] -> p[2], p[4] -> p[3], p[5] -> p[1], p[6] -> -p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][4], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][3], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[4], 
     p[3] -> p[2], p[4] -> p[3], p[5] -> p[1], p[6] -> -p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][4], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][3], 
     \[Epsilon][5] -> \[Epsilon][1]}}] + 
  RG[bg[6], {1, 1, -1, -1, -1, -1, 1, 1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}}] + 
  RG[bg[6], {1, 1, -1, -1, -1, -1, 1, 1}, 
   {{p[1] -> p[1], p[2] -> p[3], p[3] -> p[4], p[4] -> p[2], p[5] -> p[5], 
     p[6] -> -p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][4], \[Epsilon][4] -> \[Epsilon][2], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[4], p[4] -> p[2], p[5] -> p[5], p[6] -> -p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][4], \[Epsilon][4] -> \[Epsilon][2], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[4], 
     p[3] -> p[3], p[4] -> p[2], p[5] -> p[5], p[6] -> -p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][4], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][2], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[4], 
     p[3] -> p[3], p[4] -> p[2], p[5] -> p[5], p[6] -> -p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][4], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][2], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[4], p[4] -> p[2], p[5] -> p[1], p[6] -> -p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][4], \[Epsilon][4] -> \[Epsilon][2], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[4], p[4] -> p[2], p[5] -> p[1], p[6] -> -p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][4], \[Epsilon][4] -> \[Epsilon][2], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[4], 
     p[3] -> p[3], p[4] -> p[2], p[5] -> p[1], p[6] -> -p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][4], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][2], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[4], 
     p[3] -> p[3], p[4] -> p[2], p[5] -> p[1], p[6] -> -p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][4], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][2], 
     \[Epsilon][5] -> \[Epsilon][1]}}], 
 RG[bg[6], {-1, -1, 1, 1, 1, 1, -1, -1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> -p[10], p[9] -> p[9], p[10] -> p[8], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> -p[10], p[9] -> p[9], p[10] -> p[8], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> -p[10], p[9] -> p[9], p[10] -> p[8], 
     \[Epsilon][1] -> \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> -p[10], p[9] -> p[9], p[10] -> p[8], 
     \[Epsilon][1] -> \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}}] + 
  RG[bg[6], {1, 1, -1, -1, -1, -1, 1, 1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}, {p[1] -> p[5], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[1], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[10], p[9] -> p[9], p[10] -> p[8], \[Epsilon][1] -> 
      \[Epsilon][5], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][1]}}], 
 RG[bg[7], {-1, -1, 1, 1}, {{p[1] -> p[2], p[2] -> p[1], p[3] -> p[3], 
     p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], 
     p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> -p[10], 
     p[10] -> -p[9], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5]}, 
    {p[1] -> p[2], p[2] -> p[3], p[3] -> p[1], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[2], p[2] -> p[3], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][2], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}}] + RG[bg[7], {1, 1, -1, -1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}}] + RG[bg[7], {1, 1, -1, -1}, 
   {{p[1] -> p[3], p[2] -> p[1], p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[3], p[2] -> p[1], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][1], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[3], p[2] -> p[2], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[3], p[2] -> p[2], 
     p[3] -> p[1], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][3], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][1], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}}], 
 RG[bg[7], {-1, -1, 1, 1}, {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], 
     p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], 
     p[9] -> -p[9], p[10] -> -p[10], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[10], p[10] -> p[9], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[9], p[10] -> -p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[10], p[10] -> p[9], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}}] + RG[bg[7], {1, 1, -1, -1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[2], 
     p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][2], 
     \[Epsilon][3] -> \[Epsilon][3], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], \[Epsilon][1] -> 
      \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}, {p[1] -> p[1], p[2] -> p[3], 
     p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], p[6] -> p[6], p[7] -> p[7], 
     p[8] -> p[8], p[9] -> -p[10], p[10] -> -p[9], 
     \[Epsilon][1] -> \[Epsilon][1], \[Epsilon][2] -> \[Epsilon][3], 
     \[Epsilon][3] -> \[Epsilon][2], \[Epsilon][4] -> \[Epsilon][4], 
     \[Epsilon][5] -> \[Epsilon][5]}}]}
