{RG[bg[1], {-1, 1, 1, -1, 1, -1, -1, 1}, 
   {{p[1] -> p[1], p[2] -> p[3], p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[1], p[2] -> p[3], p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[3], p[2] -> p[1], p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[3], p[2] -> p[1], p[3] -> p[2], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[6], p[2] -> p[7], p[3] -> p[5], p[4] -> p[4], p[5] -> p[2], 
     p[6] -> p[1], p[7] -> p[3], p[8] -> -p[11], p[9] -> -p[10], 
     p[10] -> -p[9], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][6], 
     \[Epsilon][2] -> \[Epsilon][7], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][2], 
     \[Epsilon][6] -> \[Epsilon][1], \[Epsilon][7] -> \[Epsilon][3]}, 
    {p[1] -> p[6], p[2] -> p[7], p[3] -> p[5], p[4] -> p[4], p[5] -> p[2], 
     p[6] -> p[3], p[7] -> p[1], p[8] -> -p[11], p[9] -> -p[10], 
     p[10] -> -p[9], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][6], 
     \[Epsilon][2] -> \[Epsilon][7], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][2], 
     \[Epsilon][6] -> \[Epsilon][3], \[Epsilon][7] -> \[Epsilon][1]}, 
    {p[1] -> p[7], p[2] -> p[6], p[3] -> p[5], p[4] -> p[4], p[5] -> p[2], 
     p[6] -> p[1], p[7] -> p[3], p[8] -> -p[11], p[9] -> -p[10], 
     p[10] -> -p[9], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][7], 
     \[Epsilon][2] -> \[Epsilon][6], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][2], 
     \[Epsilon][6] -> \[Epsilon][1], \[Epsilon][7] -> \[Epsilon][3]}, 
    {p[1] -> p[7], p[2] -> p[6], p[3] -> p[5], p[4] -> p[4], p[5] -> p[2], 
     p[6] -> p[3], p[7] -> p[1], p[8] -> -p[11], p[9] -> -p[10], 
     p[10] -> -p[9], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][7], 
     \[Epsilon][2] -> \[Epsilon][6], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][2], 
     \[Epsilon][6] -> \[Epsilon][3], \[Epsilon][7] -> \[Epsilon][1]}}] + 
  RG[bg[1], {1, -1, -1, 1, -1, 1, 1, -1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[6], p[2] -> p[7], p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], 
     p[6] -> p[1], p[7] -> p[2], p[8] -> -p[11], p[9] -> -p[10], 
     p[10] -> -p[9], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][6], 
     \[Epsilon][2] -> \[Epsilon][7], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][3], 
     \[Epsilon][6] -> \[Epsilon][1], \[Epsilon][7] -> \[Epsilon][2]}, 
    {p[1] -> p[6], p[2] -> p[7], p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], 
     p[6] -> p[2], p[7] -> p[1], p[8] -> -p[11], p[9] -> -p[10], 
     p[10] -> -p[9], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][6], 
     \[Epsilon][2] -> \[Epsilon][7], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][3], 
     \[Epsilon][6] -> \[Epsilon][2], \[Epsilon][7] -> \[Epsilon][1]}, 
    {p[1] -> p[7], p[2] -> p[6], p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], 
     p[6] -> p[1], p[7] -> p[2], p[8] -> -p[11], p[9] -> -p[10], 
     p[10] -> -p[9], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][7], 
     \[Epsilon][2] -> \[Epsilon][6], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][3], 
     \[Epsilon][6] -> \[Epsilon][1], \[Epsilon][7] -> \[Epsilon][2]}, 
    {p[1] -> p[7], p[2] -> p[6], p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], 
     p[6] -> p[2], p[7] -> p[1], p[8] -> -p[11], p[9] -> -p[10], 
     p[10] -> -p[9], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][7], 
     \[Epsilon][2] -> \[Epsilon][6], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][3], 
     \[Epsilon][6] -> \[Epsilon][2], \[Epsilon][7] -> \[Epsilon][1]}}] + 
  RG[bg[1], {1, -1, -1, 1, -1, 1, 1, -1}, 
   {{p[1] -> p[2], p[2] -> p[3], p[3] -> p[1], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> -p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[2], p[2] -> p[3], p[3] -> p[1], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> -p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[3], p[2] -> p[2], p[3] -> p[1], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> -p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[3], p[2] -> p[2], p[3] -> p[1], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> -p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[6], p[2] -> p[7], p[3] -> p[5], p[4] -> p[4], p[5] -> p[1], 
     p[6] -> p[2], p[7] -> p[3], p[8] -> -p[11], p[9] -> -p[10], 
     p[10] -> -p[9], p[11] -> p[8], \[Epsilon][1] -> \[Epsilon][6], 
     \[Epsilon][2] -> \[Epsilon][7], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][1], 
     \[Epsilon][6] -> \[Epsilon][2], \[Epsilon][7] -> \[Epsilon][3]}, 
    {p[1] -> p[6], p[2] -> p[7], p[3] -> p[5], p[4] -> p[4], p[5] -> p[1], 
     p[6] -> p[3], p[7] -> p[2], p[8] -> -p[11], p[9] -> -p[10], 
     p[10] -> -p[9], p[11] -> p[8], \[Epsilon][1] -> \[Epsilon][6], 
     \[Epsilon][2] -> \[Epsilon][7], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][1], 
     \[Epsilon][6] -> \[Epsilon][3], \[Epsilon][7] -> \[Epsilon][2]}, 
    {p[1] -> p[7], p[2] -> p[6], p[3] -> p[5], p[4] -> p[4], p[5] -> p[1], 
     p[6] -> p[2], p[7] -> p[3], p[8] -> -p[11], p[9] -> -p[10], 
     p[10] -> -p[9], p[11] -> p[8], \[Epsilon][1] -> \[Epsilon][7], 
     \[Epsilon][2] -> \[Epsilon][6], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][1], 
     \[Epsilon][6] -> \[Epsilon][2], \[Epsilon][7] -> \[Epsilon][3]}, 
    {p[1] -> p[7], p[2] -> p[6], p[3] -> p[5], p[4] -> p[4], p[5] -> p[1], 
     p[6] -> p[3], p[7] -> p[2], p[8] -> -p[11], p[9] -> -p[10], 
     p[10] -> -p[9], p[11] -> p[8], \[Epsilon][1] -> \[Epsilon][7], 
     \[Epsilon][2] -> \[Epsilon][6], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][1], 
     \[Epsilon][6] -> \[Epsilon][3], \[Epsilon][7] -> \[Epsilon][2]}}], 
 RG[bg[1], {-1, 1, 1, -1, 1, -1, -1, 1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[6], p[2] -> p[7], p[3] -> p[5], p[4] -> p[3], p[5] -> p[4], 
     p[6] -> p[1], p[7] -> p[2], p[8] -> -p[11], p[9] -> -p[10], 
     p[10] -> -p[9], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][6], 
     \[Epsilon][2] -> \[Epsilon][7], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][4], 
     \[Epsilon][6] -> \[Epsilon][1], \[Epsilon][7] -> \[Epsilon][2]}, 
    {p[1] -> p[6], p[2] -> p[7], p[3] -> p[5], p[4] -> p[3], p[5] -> p[4], 
     p[6] -> p[2], p[7] -> p[1], p[8] -> -p[11], p[9] -> -p[10], 
     p[10] -> -p[9], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][6], 
     \[Epsilon][2] -> \[Epsilon][7], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][4], 
     \[Epsilon][6] -> \[Epsilon][2], \[Epsilon][7] -> \[Epsilon][1]}, 
    {p[1] -> p[7], p[2] -> p[6], p[3] -> p[5], p[4] -> p[3], p[5] -> p[4], 
     p[6] -> p[1], p[7] -> p[2], p[8] -> -p[11], p[9] -> -p[10], 
     p[10] -> -p[9], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][7], 
     \[Epsilon][2] -> \[Epsilon][6], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][4], 
     \[Epsilon][6] -> \[Epsilon][1], \[Epsilon][7] -> \[Epsilon][2]}, 
    {p[1] -> p[7], p[2] -> p[6], p[3] -> p[5], p[4] -> p[3], p[5] -> p[4], 
     p[6] -> p[2], p[7] -> p[1], p[8] -> -p[11], p[9] -> -p[10], 
     p[10] -> -p[9], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][7], 
     \[Epsilon][2] -> \[Epsilon][6], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][4], 
     \[Epsilon][6] -> \[Epsilon][2], \[Epsilon][7] -> \[Epsilon][1]}}] + 
  RG[bg[1], {1, -1, -1, 1, -1, 1, 1, -1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[6], p[2] -> p[7], p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], 
     p[6] -> p[1], p[7] -> p[2], p[8] -> -p[11], p[9] -> -p[10], 
     p[10] -> -p[9], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][6], 
     \[Epsilon][2] -> \[Epsilon][7], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][3], 
     \[Epsilon][6] -> \[Epsilon][1], \[Epsilon][7] -> \[Epsilon][2]}, 
    {p[1] -> p[6], p[2] -> p[7], p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], 
     p[6] -> p[2], p[7] -> p[1], p[8] -> -p[11], p[9] -> -p[10], 
     p[10] -> -p[9], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][6], 
     \[Epsilon][2] -> \[Epsilon][7], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][3], 
     \[Epsilon][6] -> \[Epsilon][2], \[Epsilon][7] -> \[Epsilon][1]}, 
    {p[1] -> p[7], p[2] -> p[6], p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], 
     p[6] -> p[1], p[7] -> p[2], p[8] -> -p[11], p[9] -> -p[10], 
     p[10] -> -p[9], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][7], 
     \[Epsilon][2] -> \[Epsilon][6], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][3], 
     \[Epsilon][6] -> \[Epsilon][1], \[Epsilon][7] -> \[Epsilon][2]}, 
    {p[1] -> p[7], p[2] -> p[6], p[3] -> p[5], p[4] -> p[4], p[5] -> p[3], 
     p[6] -> p[2], p[7] -> p[1], p[8] -> -p[11], p[9] -> -p[10], 
     p[10] -> -p[9], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][7], 
     \[Epsilon][2] -> \[Epsilon][6], \[Epsilon][3] -> \[Epsilon][5], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][3], 
     \[Epsilon][6] -> \[Epsilon][2], \[Epsilon][7] -> \[Epsilon][1]}}] + 
  RG[bg[2], {1, -1, -1, 1, -1, 1, 1, -1, -1, 1, 1, -1, 1, -1, -1, 1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[1], p[4] -> p[2], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[1], p[4] -> p[2], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[1], p[4] -> p[2], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[1], p[4] -> p[2], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}}], 
 RG[bg[2], {-1, 1, 1, -1, 1, -1, -1, 1, 1, -1, -1, 1, -1, 1, 1, -1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[6], p[4] -> p[7], p[5] -> p[5], 
     p[6] -> p[3], p[7] -> p[4], p[8] -> p[8], p[9] -> p[11], 
     p[10] -> -p[10], p[11] -> p[9], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][6], 
     \[Epsilon][4] -> \[Epsilon][7], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][3], \[Epsilon][7] -> \[Epsilon][4]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[6], p[4] -> p[7], p[5] -> p[5], 
     p[6] -> p[4], p[7] -> p[3], p[8] -> p[8], p[9] -> p[11], 
     p[10] -> -p[10], p[11] -> p[9], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][6], 
     \[Epsilon][4] -> \[Epsilon][7], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][4], \[Epsilon][7] -> \[Epsilon][3]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[7], p[4] -> p[6], p[5] -> p[5], 
     p[6] -> p[3], p[7] -> p[4], p[8] -> p[8], p[9] -> p[11], 
     p[10] -> -p[10], p[11] -> p[9], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][7], 
     \[Epsilon][4] -> \[Epsilon][6], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][3], \[Epsilon][7] -> \[Epsilon][4]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[7], p[4] -> p[6], p[5] -> p[5], 
     p[6] -> p[4], p[7] -> p[3], p[8] -> p[8], p[9] -> p[11], 
     p[10] -> -p[10], p[11] -> p[9], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][7], 
     \[Epsilon][4] -> \[Epsilon][6], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][4], \[Epsilon][7] -> \[Epsilon][3]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[6], p[4] -> p[7], p[5] -> p[5], 
     p[6] -> p[3], p[7] -> p[4], p[8] -> p[8], p[9] -> p[11], 
     p[10] -> -p[10], p[11] -> p[9], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][6], 
     \[Epsilon][4] -> \[Epsilon][7], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][3], \[Epsilon][7] -> \[Epsilon][4]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[6], p[4] -> p[7], p[5] -> p[5], 
     p[6] -> p[4], p[7] -> p[3], p[8] -> p[8], p[9] -> p[11], 
     p[10] -> -p[10], p[11] -> p[9], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][6], 
     \[Epsilon][4] -> \[Epsilon][7], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][4], \[Epsilon][7] -> \[Epsilon][3]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[7], p[4] -> p[6], p[5] -> p[5], 
     p[6] -> p[3], p[7] -> p[4], p[8] -> p[8], p[9] -> p[11], 
     p[10] -> -p[10], p[11] -> p[9], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][7], 
     \[Epsilon][4] -> \[Epsilon][6], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][3], \[Epsilon][7] -> \[Epsilon][4]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[7], p[4] -> p[6], p[5] -> p[5], 
     p[6] -> p[4], p[7] -> p[3], p[8] -> p[8], p[9] -> p[11], 
     p[10] -> -p[10], p[11] -> p[9], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][7], 
     \[Epsilon][4] -> \[Epsilon][6], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][4], \[Epsilon][7] -> \[Epsilon][3]}, 
    {p[1] -> p[6], p[2] -> p[7], p[3] -> p[1], p[4] -> p[2], p[5] -> p[5], 
     p[6] -> p[3], p[7] -> p[4], p[8] -> -p[11], p[9] -> -p[8], 
     p[10] -> -p[10], p[11] -> p[9], \[Epsilon][1] -> \[Epsilon][6], 
     \[Epsilon][2] -> \[Epsilon][7], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][3], \[Epsilon][7] -> \[Epsilon][4]}, 
    {p[1] -> p[6], p[2] -> p[7], p[3] -> p[1], p[4] -> p[2], p[5] -> p[5], 
     p[6] -> p[4], p[7] -> p[3], p[8] -> -p[11], p[9] -> -p[8], 
     p[10] -> -p[10], p[11] -> p[9], \[Epsilon][1] -> \[Epsilon][6], 
     \[Epsilon][2] -> \[Epsilon][7], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][4], \[Epsilon][7] -> \[Epsilon][3]}, 
    {p[1] -> p[6], p[2] -> p[7], p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], 
     p[6] -> p[3], p[7] -> p[4], p[8] -> -p[11], p[9] -> -p[8], 
     p[10] -> -p[10], p[11] -> p[9], \[Epsilon][1] -> \[Epsilon][6], 
     \[Epsilon][2] -> \[Epsilon][7], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][3], \[Epsilon][7] -> \[Epsilon][4]}, 
    {p[1] -> p[6], p[2] -> p[7], p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], 
     p[6] -> p[4], p[7] -> p[3], p[8] -> -p[11], p[9] -> -p[8], 
     p[10] -> -p[10], p[11] -> p[9], \[Epsilon][1] -> \[Epsilon][6], 
     \[Epsilon][2] -> \[Epsilon][7], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][4], \[Epsilon][7] -> \[Epsilon][3]}, 
    {p[1] -> p[7], p[2] -> p[6], p[3] -> p[1], p[4] -> p[2], p[5] -> p[5], 
     p[6] -> p[3], p[7] -> p[4], p[8] -> -p[11], p[9] -> -p[8], 
     p[10] -> -p[10], p[11] -> p[9], \[Epsilon][1] -> \[Epsilon][7], 
     \[Epsilon][2] -> \[Epsilon][6], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][3], \[Epsilon][7] -> \[Epsilon][4]}, 
    {p[1] -> p[7], p[2] -> p[6], p[3] -> p[1], p[4] -> p[2], p[5] -> p[5], 
     p[6] -> p[4], p[7] -> p[3], p[8] -> -p[11], p[9] -> -p[8], 
     p[10] -> -p[10], p[11] -> p[9], \[Epsilon][1] -> \[Epsilon][7], 
     \[Epsilon][2] -> \[Epsilon][6], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][4], \[Epsilon][7] -> \[Epsilon][3]}, 
    {p[1] -> p[7], p[2] -> p[6], p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], 
     p[6] -> p[3], p[7] -> p[4], p[8] -> -p[11], p[9] -> -p[8], 
     p[10] -> -p[10], p[11] -> p[9], \[Epsilon][1] -> \[Epsilon][7], 
     \[Epsilon][2] -> \[Epsilon][6], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][3], \[Epsilon][7] -> \[Epsilon][4]}, 
    {p[1] -> p[7], p[2] -> p[6], p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], 
     p[6] -> p[4], p[7] -> p[3], p[8] -> -p[11], p[9] -> -p[8], 
     p[10] -> -p[10], p[11] -> p[9], \[Epsilon][1] -> \[Epsilon][7], 
     \[Epsilon][2] -> \[Epsilon][6], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][4], \[Epsilon][7] -> \[Epsilon][3]}}] + 
  RG[bg[2], {1, -1, -1, 1, -1, 1, 1, -1, -1, 1, 1, -1, 1, -1, -1, 1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[1], p[4] -> p[2], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[1], p[4] -> p[2], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[1], p[4] -> p[2], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[1], p[4] -> p[2], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}}] + 
  RG[bg[2], {1, -1, -1, 1, -1, 1, 1, -1, -1, 1, 1, -1, 1, -1, -1, 1}, 
   {{p[1] -> p[3], p[2] -> p[4], p[3] -> p[6], p[4] -> p[7], p[5] -> p[5], 
     p[6] -> p[1], p[7] -> p[2], p[8] -> -p[9], p[9] -> p[11], 
     p[10] -> p[10], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][6], 
     \[Epsilon][4] -> \[Epsilon][7], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][1], \[Epsilon][7] -> \[Epsilon][2]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[6], p[4] -> p[7], p[5] -> p[5], 
     p[6] -> p[2], p[7] -> p[1], p[8] -> -p[9], p[9] -> p[11], 
     p[10] -> p[10], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][6], 
     \[Epsilon][4] -> \[Epsilon][7], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][2], \[Epsilon][7] -> \[Epsilon][1]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[7], p[4] -> p[6], p[5] -> p[5], 
     p[6] -> p[1], p[7] -> p[2], p[8] -> -p[9], p[9] -> p[11], 
     p[10] -> p[10], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][7], 
     \[Epsilon][4] -> \[Epsilon][6], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][1], \[Epsilon][7] -> \[Epsilon][2]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[7], p[4] -> p[6], p[5] -> p[5], 
     p[6] -> p[2], p[7] -> p[1], p[8] -> -p[9], p[9] -> p[11], 
     p[10] -> p[10], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][7], 
     \[Epsilon][4] -> \[Epsilon][6], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][2], \[Epsilon][7] -> \[Epsilon][1]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[6], p[4] -> p[7], p[5] -> p[5], 
     p[6] -> p[1], p[7] -> p[2], p[8] -> -p[9], p[9] -> p[11], 
     p[10] -> p[10], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][6], 
     \[Epsilon][4] -> \[Epsilon][7], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][1], \[Epsilon][7] -> \[Epsilon][2]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[6], p[4] -> p[7], p[5] -> p[5], 
     p[6] -> p[2], p[7] -> p[1], p[8] -> -p[9], p[9] -> p[11], 
     p[10] -> p[10], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][6], 
     \[Epsilon][4] -> \[Epsilon][7], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][2], \[Epsilon][7] -> \[Epsilon][1]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[7], p[4] -> p[6], p[5] -> p[5], 
     p[6] -> p[1], p[7] -> p[2], p[8] -> -p[9], p[9] -> p[11], 
     p[10] -> p[10], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][7], 
     \[Epsilon][4] -> \[Epsilon][6], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][1], \[Epsilon][7] -> \[Epsilon][2]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[7], p[4] -> p[6], p[5] -> p[5], 
     p[6] -> p[2], p[7] -> p[1], p[8] -> -p[9], p[9] -> p[11], 
     p[10] -> p[10], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][7], 
     \[Epsilon][4] -> \[Epsilon][6], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][2], \[Epsilon][7] -> \[Epsilon][1]}, 
    {p[1] -> p[6], p[2] -> p[7], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[1], p[7] -> p[2], p[8] -> -p[11], p[9] -> p[9], 
     p[10] -> p[10], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][6], 
     \[Epsilon][2] -> \[Epsilon][7], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][1], \[Epsilon][7] -> \[Epsilon][2]}, 
    {p[1] -> p[6], p[2] -> p[7], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[2], p[7] -> p[1], p[8] -> -p[11], p[9] -> p[9], 
     p[10] -> p[10], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][6], 
     \[Epsilon][2] -> \[Epsilon][7], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][2], \[Epsilon][7] -> \[Epsilon][1]}, 
    {p[1] -> p[6], p[2] -> p[7], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     p[6] -> p[1], p[7] -> p[2], p[8] -> -p[11], p[9] -> p[9], 
     p[10] -> p[10], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][6], 
     \[Epsilon][2] -> \[Epsilon][7], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][1], \[Epsilon][7] -> \[Epsilon][2]}, 
    {p[1] -> p[6], p[2] -> p[7], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     p[6] -> p[2], p[7] -> p[1], p[8] -> -p[11], p[9] -> p[9], 
     p[10] -> p[10], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][6], 
     \[Epsilon][2] -> \[Epsilon][7], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][2], \[Epsilon][7] -> \[Epsilon][1]}, 
    {p[1] -> p[7], p[2] -> p[6], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[1], p[7] -> p[2], p[8] -> -p[11], p[9] -> p[9], 
     p[10] -> p[10], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][7], 
     \[Epsilon][2] -> \[Epsilon][6], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][1], \[Epsilon][7] -> \[Epsilon][2]}, 
    {p[1] -> p[7], p[2] -> p[6], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[2], p[7] -> p[1], p[8] -> -p[11], p[9] -> p[9], 
     p[10] -> p[10], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][7], 
     \[Epsilon][2] -> \[Epsilon][6], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][2], \[Epsilon][7] -> \[Epsilon][1]}, 
    {p[1] -> p[7], p[2] -> p[6], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     p[6] -> p[1], p[7] -> p[2], p[8] -> -p[11], p[9] -> p[9], 
     p[10] -> p[10], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][7], 
     \[Epsilon][2] -> \[Epsilon][6], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][1], \[Epsilon][7] -> \[Epsilon][2]}, 
    {p[1] -> p[7], p[2] -> p[6], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     p[6] -> p[2], p[7] -> p[1], p[8] -> -p[11], p[9] -> p[9], 
     p[10] -> p[10], p[11] -> -p[8], \[Epsilon][1] -> \[Epsilon][7], 
     \[Epsilon][2] -> \[Epsilon][6], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][2], \[Epsilon][7] -> \[Epsilon][1]}}], 
 RG[bg[2], {-1, 1, 1, -1, 1, -1, -1, 1, 1, -1, -1, 1, -1, 1, 1, -1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[6], 
     p[6] -> p[5], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][6], 
     \[Epsilon][6] -> \[Epsilon][5], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[6], 
     p[6] -> p[7], p[7] -> p[5], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][6], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][5]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[4], p[4] -> p[3], p[5] -> p[6], 
     p[6] -> p[5], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][6], 
     \[Epsilon][6] -> \[Epsilon][5], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[4], p[4] -> p[3], p[5] -> p[6], 
     p[6] -> p[7], p[7] -> p[5], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][6], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][5]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[3], p[4] -> p[4], p[5] -> p[6], 
     p[6] -> p[5], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][6], 
     \[Epsilon][6] -> \[Epsilon][5], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[3], p[4] -> p[4], p[5] -> p[6], 
     p[6] -> p[7], p[7] -> p[5], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][6], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][5]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[4], p[4] -> p[3], p[5] -> p[6], 
     p[6] -> p[5], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][6], 
     \[Epsilon][6] -> \[Epsilon][5], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[4], p[4] -> p[3], p[5] -> p[6], 
     p[6] -> p[7], p[7] -> p[5], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][6], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][5]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[1], p[4] -> p[2], p[5] -> p[6], 
     p[6] -> p[5], p[7] -> p[7], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][6], 
     \[Epsilon][6] -> \[Epsilon][5], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[1], p[4] -> p[2], p[5] -> p[6], 
     p[6] -> p[7], p[7] -> p[5], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][6], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][5]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[2], p[4] -> p[1], p[5] -> p[6], 
     p[6] -> p[5], p[7] -> p[7], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][6], 
     \[Epsilon][6] -> \[Epsilon][5], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[2], p[4] -> p[1], p[5] -> p[6], 
     p[6] -> p[7], p[7] -> p[5], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][6], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][5]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[1], p[4] -> p[2], p[5] -> p[6], 
     p[6] -> p[5], p[7] -> p[7], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][6], 
     \[Epsilon][6] -> \[Epsilon][5], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[1], p[4] -> p[2], p[5] -> p[6], 
     p[6] -> p[7], p[7] -> p[5], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][6], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][5]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[2], p[4] -> p[1], p[5] -> p[6], 
     p[6] -> p[5], p[7] -> p[7], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][6], 
     \[Epsilon][6] -> \[Epsilon][5], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[2], p[4] -> p[1], p[5] -> p[6], 
     p[6] -> p[7], p[7] -> p[5], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][6], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][5]}}] + 
  RG[bg[2], {1, -1, -1, 1, -1, 1, 1, -1, -1, 1, 1, -1, 1, -1, -1, 1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[3], p[4] -> p[4], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[4], p[4] -> p[3], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[1], p[4] -> p[2], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[1], p[4] -> p[2], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[1], p[4] -> p[2], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[1], p[4] -> p[2], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], 
     p[6] -> p[6], p[7] -> p[7], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][7]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[2], p[4] -> p[1], p[5] -> p[5], 
     p[6] -> p[7], p[7] -> p[6], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][5], 
     \[Epsilon][6] -> \[Epsilon][7], \[Epsilon][7] -> \[Epsilon][6]}}] + 
  RG[bg[2], {1, -1, -1, 1, -1, 1, 1, -1, -1, 1, 1, -1, 1, -1, -1, 1}, 
   {{p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[7], 
     p[6] -> p[5], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][7], 
     \[Epsilon][6] -> \[Epsilon][5], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[3], p[4] -> p[4], p[5] -> p[7], 
     p[6] -> p[6], p[7] -> p[5], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][7], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][5]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[4], p[4] -> p[3], p[5] -> p[7], 
     p[6] -> p[5], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][7], 
     \[Epsilon][6] -> \[Epsilon][5], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[1], p[2] -> p[2], p[3] -> p[4], p[4] -> p[3], p[5] -> p[7], 
     p[6] -> p[6], p[7] -> p[5], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][1], 
     \[Epsilon][2] -> \[Epsilon][2], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][7], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][5]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[3], p[4] -> p[4], p[5] -> p[7], 
     p[6] -> p[5], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][7], 
     \[Epsilon][6] -> \[Epsilon][5], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[3], p[4] -> p[4], p[5] -> p[7], 
     p[6] -> p[6], p[7] -> p[5], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][3], 
     \[Epsilon][4] -> \[Epsilon][4], \[Epsilon][5] -> \[Epsilon][7], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][5]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[4], p[4] -> p[3], p[5] -> p[7], 
     p[6] -> p[5], p[7] -> p[6], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][7], 
     \[Epsilon][6] -> \[Epsilon][5], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[2], p[2] -> p[1], p[3] -> p[4], p[4] -> p[3], p[5] -> p[7], 
     p[6] -> p[6], p[7] -> p[5], p[8] -> p[8], p[9] -> p[9], p[10] -> p[10], 
     p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][2], 
     \[Epsilon][2] -> \[Epsilon][1], \[Epsilon][3] -> \[Epsilon][4], 
     \[Epsilon][4] -> \[Epsilon][3], \[Epsilon][5] -> \[Epsilon][7], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][5]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[1], p[4] -> p[2], p[5] -> p[7], 
     p[6] -> p[5], p[7] -> p[6], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][7], 
     \[Epsilon][6] -> \[Epsilon][5], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[1], p[4] -> p[2], p[5] -> p[7], 
     p[6] -> p[6], p[7] -> p[5], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][7], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][5]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[2], p[4] -> p[1], p[5] -> p[7], 
     p[6] -> p[5], p[7] -> p[6], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][7], 
     \[Epsilon][6] -> \[Epsilon][5], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[3], p[2] -> p[4], p[3] -> p[2], p[4] -> p[1], p[5] -> p[7], 
     p[6] -> p[6], p[7] -> p[5], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][3], 
     \[Epsilon][2] -> \[Epsilon][4], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][7], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][5]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[1], p[4] -> p[2], p[5] -> p[7], 
     p[6] -> p[5], p[7] -> p[6], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][7], 
     \[Epsilon][6] -> \[Epsilon][5], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[1], p[4] -> p[2], p[5] -> p[7], 
     p[6] -> p[6], p[7] -> p[5], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][1], 
     \[Epsilon][4] -> \[Epsilon][2], \[Epsilon][5] -> \[Epsilon][7], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][5]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[2], p[4] -> p[1], p[5] -> p[7], 
     p[6] -> p[5], p[7] -> p[6], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][7], 
     \[Epsilon][6] -> \[Epsilon][5], \[Epsilon][7] -> \[Epsilon][6]}, 
    {p[1] -> p[4], p[2] -> p[3], p[3] -> p[2], p[4] -> p[1], p[5] -> p[7], 
     p[6] -> p[6], p[7] -> p[5], p[8] -> -p[9], p[9] -> -p[8], 
     p[10] -> p[10], p[11] -> p[11], \[Epsilon][1] -> \[Epsilon][4], 
     \[Epsilon][2] -> \[Epsilon][3], \[Epsilon][3] -> \[Epsilon][2], 
     \[Epsilon][4] -> \[Epsilon][1], \[Epsilon][5] -> \[Epsilon][7], 
     \[Epsilon][6] -> \[Epsilon][6], \[Epsilon][7] -> \[Epsilon][5]}}]}
